language: python

python:
    - "3.3"
    - "3.2"
    - "3.1"
    - "3.0"
    - "2.7"

install:
    - "pip install -r requirements.txt"

script: python -m unittest --verbose --catch --failfast tests.py
